FROM openjdk:8
VOLUME /tmp
ADD ./target/services-ipau-problematica-location-0.0.1-SNAPSHOT.jar services-ipau-problematica-location.jar
ENTRYPOINT ["java","-jar","/services-ipau-problematica-location.jar"]